// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: business/business.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BusinessService_FindBusinessById_FullMethodName               = "/schedulr.business.v1.BusinessService/FindBusinessById"
	BusinessService_CreateBusinessFromRegistration_FullMethodName = "/schedulr.business.v1.BusinessService/CreateBusinessFromRegistration"
)

// BusinessServiceClient is the client API for BusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusinessServiceClient interface {
	FindBusinessById(ctx context.Context, in *FindBusinessByIdRequest, opts ...grpc.CallOption) (*FindBusinessByIdResponse, error)
	CreateBusinessFromRegistration(ctx context.Context, in *CreateBusinessFromRegistrationRequest, opts ...grpc.CallOption) (*CreateBusinessFromRegistrationResponse, error)
}

type businessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessServiceClient(cc grpc.ClientConnInterface) BusinessServiceClient {
	return &businessServiceClient{cc}
}

func (c *businessServiceClient) FindBusinessById(ctx context.Context, in *FindBusinessByIdRequest, opts ...grpc.CallOption) (*FindBusinessByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindBusinessByIdResponse)
	err := c.cc.Invoke(ctx, BusinessService_FindBusinessById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) CreateBusinessFromRegistration(ctx context.Context, in *CreateBusinessFromRegistrationRequest, opts ...grpc.CallOption) (*CreateBusinessFromRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBusinessFromRegistrationResponse)
	err := c.cc.Invoke(ctx, BusinessService_CreateBusinessFromRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServiceServer is the server API for BusinessService service.
// All implementations must embed UnimplementedBusinessServiceServer
// for forward compatibility.
type BusinessServiceServer interface {
	FindBusinessById(context.Context, *FindBusinessByIdRequest) (*FindBusinessByIdResponse, error)
	CreateBusinessFromRegistration(context.Context, *CreateBusinessFromRegistrationRequest) (*CreateBusinessFromRegistrationResponse, error)
	mustEmbedUnimplementedBusinessServiceServer()
}

// UnimplementedBusinessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusinessServiceServer struct{}

func (UnimplementedBusinessServiceServer) FindBusinessById(context.Context, *FindBusinessByIdRequest) (*FindBusinessByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBusinessById not implemented")
}
func (UnimplementedBusinessServiceServer) CreateBusinessFromRegistration(context.Context, *CreateBusinessFromRegistrationRequest) (*CreateBusinessFromRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusinessFromRegistration not implemented")
}
func (UnimplementedBusinessServiceServer) mustEmbedUnimplementedBusinessServiceServer() {}
func (UnimplementedBusinessServiceServer) testEmbeddedByValue()                         {}

// UnsafeBusinessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessServiceServer will
// result in compilation errors.
type UnsafeBusinessServiceServer interface {
	mustEmbedUnimplementedBusinessServiceServer()
}

func RegisterBusinessServiceServer(s grpc.ServiceRegistrar, srv BusinessServiceServer) {
	// If the following call pancis, it indicates UnimplementedBusinessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BusinessService_ServiceDesc, srv)
}

func _BusinessService_FindBusinessById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBusinessByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).FindBusinessById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_FindBusinessById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).FindBusinessById(ctx, req.(*FindBusinessByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_CreateBusinessFromRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessFromRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).CreateBusinessFromRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BusinessService_CreateBusinessFromRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).CreateBusinessFromRegistration(ctx, req.(*CreateBusinessFromRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BusinessService_ServiceDesc is the grpc.ServiceDesc for BusinessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BusinessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedulr.business.v1.BusinessService",
	HandlerType: (*BusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBusinessById",
			Handler:    _BusinessService_FindBusinessById_Handler,
		},
		{
			MethodName: "CreateBusinessFromRegistration",
			Handler:    _BusinessService_CreateBusinessFromRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business/business.proto",
}
