services:
  schedulr-user-db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U schedulr -d schedulr_user" ]
      interval: 5s
      retries: 10
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - schedulr_user_network

  schedulr-user-service:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      schedulr-user-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "grpc_health_probe", "-addr=localhost:8080"]
      retries: 3
      interval: 60s
      start_period: 5s
      timeout: 30s
    networks:
      - schedulr_user_network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}

networks:
  schedulr_user_network:
    driver: bridge