syntax = "proto3";

package schedulr.user.v1;

option go_package = "github.com/virgiawanly/schedulr-backend/protogen/go/user/v1";

import "google/protobuf/timestamp.proto";

service UserService {
  rpc FindUserById(FindUserByIdRequest) returns (FindUserByIdResponse);
  rpc FindUserByAccountId(FindUserByAccountIdRequest) returns (FindUserByAccountIdResponse);
  rpc CreateUserFromRegistration(CreateUserFromRegistrationRequest) returns (CreateUserFromRegistrationResponse);
  rpc UpdateUserByAccountId(UpdateUserByAccountIdRequest) returns (UpdateUserByAccountIdResponse);
}

message User {
  string id = 1;
  string business_id = 2;
  string account_id = 3;
  string first_name = 4;
  optional string last_name = 5;
  optional string phone = 6;
  optional string address_1 = 7;
  optional string address_2 = 8;
  optional string city = 9;
  optional string state = 10;
  optional string zipcode = 11;
  optional string country = 12;
  optional string image_path = 13;
  optional string language = 14;
  optional double labour_cost = 15;

  optional google.protobuf.Timestamp created_at = 100;
  optional google.protobuf.Timestamp updated_at = 101;
  optional google.protobuf.Timestamp deleted_at = 102;
}

message FindUserByIdRequest {
  string id = 1;
}

message FindUserByIdResponse {
  User user = 1;
}

message FindUserByAccountIdRequest {
  string account_id = 1 [json_name = "account_id"];
}

message FindUserByAccountIdResponse {
  optional User user = 1;
}

message CreateUserFromRegistrationRequest {
  string account_id = 1 [json_name = "account_id"];
  string first_name = 2 [json_name = "first_name"];
  optional string last_name = 3 [json_name = "last_name"];
  optional string phone = 4;
  optional string address_1 = 5 [json_name = "address_1"];
  optional string address_2 = 6 [json_name = "address_2"];
  optional string city = 7;
  optional string state = 8;
  optional string zipcode = 9;
  optional string country = 10;
}

message CreateUserFromRegistrationResponse {
  User user = 1;
}

message UpdateUserByAccountIdRequest {
  string account_id = 1 [json_name = "account_id"];
  string first_name = 2 [json_name = "first_name"];
  optional string last_name = 3 [json_name = "last_name"];
  optional string phone = 4;
  optional string address_1 = 5 [json_name = "address_1"];
  optional string address_2 = 6 [json_name = "address_2"];
  optional string city = 7;
  optional string state = 8;
  optional string zipcode = 9;
  optional string country = 10;
}

message UpdateUserByAccountIdResponse {
  User user = 1;
}
